### ISSUE TITLE
[BUG] Docker no such file error

### ISSUE THREAD

**Issue by PhoenixGames-Phoenix** [PhoenixGames-Phoenix/phx-bot#1]
**Bug Description**
After building and running a Docker Container, i get a no such file or directory error after the bot tries to access the config.

**To Reproduce**
1. Run docker build
2. Run docker run -d <tag>

**Error Message**
internal/fs/utils.js:269
throw err;
^
Error: ENOENT: no such file or directory, open '../config/config.json'
at Object.openSync (fs.js:462:3)
at Object.readFileSync (fs.js:364:35)
at Object.<anonymous> (/bot/src/config.js:4:27)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/bot/src/index.js:3:27) {
errno: -2,
syscall: 'open',
code: 'ENOENT',
path: '../config/config.json'
}

**Expected behavior**
The docker container should run exactly the same as running 'node .' in the src/ directory

**Additional Info**
Docker version: 19.03.12, build 48a66213fe

**Comment by PhoenixGames-Phoenix** [comment]
Fixed in commit 87e2a9e51b3ae13e9bda0063513a9d3b7d32d05e
